### PR TITLE
LPS-79495 SF

### PR DESCRIPTION
**Pull request by gamerson**

### CODE REVIEW

**Comment by gamerson** [comment]
see comments from here; https://github.com/gamerson/liferay-portal/pull/111#pullrequestreview-117027023

**Comment by christopherbryanboyd** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by christopherbryanboyd** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by christopherbryanboyd** [comment]
Pull request submitted to https://github.com/gamerson/liferay-portal/pull/114. [See changes here.](https://github.com/christopherbryanboyd/liferay-portal/compare/4eba46525c2b~1...4eba46525c2b) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
