### PR TITLE
LPS-79417 Using compileOnly dependencies

### PR DESCRIPTION
**Pull request by 4lejandrito**
Follow up of https://github.com/gamerson/liferay-portal/pull/97. 

Hi @christopherbryanboyd & @gamerson,

Sorry for the late response, I was on vacation since Friday.

I have removed the extra parameter and used `className` everywhere. The tests went further and are now complaining about the dependencies:
```
* What went wrong:
    A problem occurred evaluating root project 'foo'.
    > Project with path ':apps:collaboration:social:social-bookmarks-api' could not be found in root project 'foo'.
```
I guess this is because some of them are not published yet and we will have to wait until they are.

Thanks!

### CODE REVIEW

**Comment by christopherbryanboyd** [comment]
Hi @4lejandrito , no problem! Thank you for refactoring the code!
We ran into this same dependency problem as you, and the same conclusion, this new template requires that the social-bookmarks-api snapshot be published.

**Comment by 4lejandrito** [comment]
Hi @christopherbryanboyd ,

The snapshot has been published. You can move forward with this when you can.

**Comment by christopherbryanboyd** [comment]
Hi @4lejandrito , thank you! I will get working on this right away.

**Comment by 4lejandrito** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/58841.

**Pull request closed without merging**
